### ISSUE TITLE
SJRK icon get hidden when when the text size is reudced.

### ISSUE THREAD

**Issue by Chaitanyassr** [fluid-project/sjrk-story-telling#63]
SJRK image(at the top left corner) is not reducing when text size is reduced from the preferences.

![Screenshot (226)](https://user-images.githubusercontent.com/30374226/78667191-20744480-78f6-11ea-85fc-698107adcf00.png)

**Comment by BlueSlug** [comment]
Great find, @Chaitanyassr! We currently use a Jira site to track all issues for this repo, so I've filed a copy of your issue report there along with some instructions for reproducing it:
https://issues.fluidproject.org/browse/SJRK-378
